services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./migrations/versions:/fastapi_ecommerce/migrations/versions
      - ./app/:/fastapi_ecommerce/app/
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:17.7-bookworm
    environment:
      POSTGRES_DB: fastapi_ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      PGDATA: /var/lib/postgresql/data
    ports:
     - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce -d fastapi_ecommerce" ]
      interval: 5s
      timeout: 3s
      retries: 3

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     pg:
  #       condition: service_healthy

volumes:
  pgdata: