"""Update Product model

Revision ID: 091903e77552
Revises: 16ceacfac8a0
Create Date: 2026-09-27 11:25:38.002151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091903e77552'
down_revision: Union[str, None] = '16ceacfac8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
