"""delete name from Base model

Revision ID: 6f98d26d85a4
Revises: c86ba5a85c8b
Create Date: 2026-10-06 12:34:37.076704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f98d26d85a4'
down_revision: Union[str, None] = 'c86ba5a85c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
