"""Set default value for product's rating

Revision ID: 789c0f0a2ca5
Revises: cc3983fbfd46
Create Date: 2026-04-29 22:35:29.356610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "789c0f0a2ca5"
down_revision: Union[str, None] = "cc3983fbfd46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
