"""Add model Review and create trigger

Revision ID: 9e5dcdf2f0d4
Revises: f3b67707c530
Create Date: 2026-10-08 21:01:10.876469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.triggers import (
    create_reviews_rating_func,
    create_reviews_rating_trigger,
    drop_reviews_rating_func,
    drop_reviews_rating_trigger,
)


# revision identifiers, used by Alembic.
revision: str = "9e5dcdf2f0d4"
down_revision: Union[str, None] = "f3b67707c530"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.String(length=5000), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("grade BETWEEN 1 AND 5", name="check_grade_range"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uq_product_user_active",
        "reviews",
        ["product_id", "user_id"],
        unique=True,
        postgresql_where="is_active = true",
    )
    # ### end Alembic commands ###

    # Add trigger for calculate product's rating
    op.execute(drop_reviews_rating_trigger)
    op.execute(drop_reviews_rating_func)
    op.execute(create_reviews_rating_func)
    op.execute(create_reviews_rating_trigger)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_uq_product_user_active",
        table_name="reviews",
        postgresql_where="is_active = true",
    )
    op.drop_table("reviews")
    # ### end Alembic commands ###

    # Remove trugger and function
    op.execute(drop_reviews_rating_trigger)
    op.execute(drop_reviews_rating_func)
