"""Update field Product.slug

Revision ID: c86ba5a85c8b
Revises: 091903e77552
Create Date: 2026-09-27 19:42:35.816211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86ba5a85c8b'
down_revision: Union[str, None] = '091903e77552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_slug', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_slug', 'products', ['slug'], unique=True)
    # ### end Alembic commands ###
