"""User role nullable=False

Revision ID: db1f6ee6f36d
Revises: ef13d262cf7b
Create Date: 2025-12-07 20:49:30.818783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db1f6ee6f36d'
down_revision: Union[str, None] = 'ef13d262cf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('ADMIN', 'SUPPLIER', 'CUSTOMER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('ADMIN', 'SUPPLIER', 'CUSTOMER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
