"""Create column role for User

Revision ID: ef13d262cf7b
Revises: 
Create Date: 2025-12-07 20:45:18.813699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef13d262cf7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'SUPPLIER', 'CUSTOMER', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('user_role', postgresql.ENUM('ADMIN', 'SUPPLIER', 'CUSTOMER', name='userrole', create_type=False), nullable=True))
    op.drop_column('users', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_role')
    sa.Enum('ADMIN', 'SUPPLIER', 'CUSTOMER', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
